---
services: docker

env:
  - distro: centos7
  - distro: centos6
  - distro: ubuntu1604
  - distro: ubuntu1404
  - distro: ubuntu1204
  - distro: debian8

script:
# Download test shim.
  - chmod +x ${PWD}/tests/test.sh

# Run tests.
  - ${PWD}/tests/test.sh