# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--cpuexecutioncap", 50]
    v.customize ["modifyvm", :id, "--memory", 256]
  end

  config.vm.define "virtualbox_phpstorm" do |virtualbox_phpstorm|
    config.vm.network "private_network", ip: "192.168.33.12"
  end

  # First, install python - if this doesn't happen, there will be errors...!
  config.vm.provision "shell" do |s|
     s.inline = "apt-get install -y python && apt-get install python-jmespath"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.inventory_path = "./inventory"
    ansible.verbose = "vvvv"
    ansible.sudo = true
    ansible.host_key_checking = false
  end
end